name: flex_http
description: A lightweight, flexible, and user-friendly HTTP client for Dart and Flutter.
version: 0.1.1
homepage: https://github.com/Deep3way/Flex_http
repository: https://github.com/Deep3way/Flex_http
issue_tracker: https://github.com/Deep3way/Flex_http/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0